use_frameworks!

platform :ios, '11.0'

target 'OpenAI_Example' do
  pod 'OpenAI', :path => '../'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end